components:
  schemas:
    Article:
      properties:
        article_title:
          description: Article title
          title: Article Title
          type: string
        article_url:
          description: Article URL
          format: uri
          maxLength: 65536
          minLength: 1
          title: Article Url
          type: string
      required:
      - article_url
      - article_title
      title: Article
      type: object
    Feed:
      properties:
        id:
          description: Feed ID
          title: Id
          type: integer
        rss_url:
          format: uri
          maxLength: 65536
          minLength: 1
          title: Rss Url
          type: string
      required:
      - rss_url
      - id
      title: Feed
      type: object
    FeedCreateResponse:
      properties:
        id:
          title: Id
          type: integer
        latest_article_url:
          description: The latest article url of the feed
          format: uri
          maxLength: 65536
          minLength: 1
          title: Latest Article Url
          type: string
        rss_url:
          format: uri
          maxLength: 65536
          minLength: 1
          title: Rss Url
          type: string
      required:
      - rss_url
      - latest_article_url
      - id
      title: FeedCreateResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    UpdatedFeedResponse:
      properties:
        articles:
          description: List of new articles
          items:
            $ref: '#/components/schemas/Article'
          title: Articles
          type: array
        id:
          description: Feed ID
          title: Id
          type: integer
        rss_url:
          format: uri
          maxLength: 65536
          minLength: 1
          title: Rss Url
          type: string
      required:
      - rss_url
      - id
      - articles
      title: UpdatedFeedResponse
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /:
    get:
      operationId: root__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Root
  /feed:
    get:
      operationId: get_all_feeds_feed_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Feed'
                title: Response Get All Feeds Feed Get
                type: array
          description: Successful Response
      summary: Get All Feeds
    post:
      operationId: create_feed_feed_post
      parameters:
      - in: query
        name: url
        required: true
        schema:
          title: Url
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeedCreateResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Create Feed
  /feed/{feed_id}:
    delete:
      operationId: delete_feed_feed__feed_id__delete
      parameters:
      - in: path
        name: feed_id
        required: true
        schema:
          title: Feed Id
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Delete Feed
    get:
      operationId: get_single_feed_feed__feed_id__get
      parameters:
      - in: path
        name: feed_id
        required: true
        schema:
          title: Feed Id
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feed'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Single Feed
  /hello:
    get:
      operationId: hello_hello_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Hello
  /update:
    get:
      operationId: return_update_feed_update_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/UpdatedFeedResponse'
                title: Response Return Update Feed Update Get
                type: array
          description: Successful Response
      summary: Return Update Feed
